kind: pipeline
type: docker
name: deploy dev (main branch)
trigger:
  branch:
    - main
steps:
  - name: build docker image
    image: plugins/docker
    settings:
      username: roxxers
      password:
        from_secret: docker_pass
      repo: roxxers/prismaticmotorsports.com
      tags: development
  - name: deploy site
    image: appleboy/drone-ssh
    settings:
      host:
        - 172.0.17.1
      username: drone
      key:
        from_secret: one_ssh_key
      port: 22
      command_timeout: 2m
      script:
        - cd /var/deploy/prismaticmotorsports.com/
        - docker compose -f compose.dev.yml up --force-recreate -d
---
kind: pipeline
type: docker
name: deploy dev (prod branch)
trigger:
  branch:
    - production
steps:
  - name: build docker image
    image: plugins/docker
    settings:
      username: roxxers
      password:
        from_secret: docker_pass
      repo: roxxers/prismaticmotorsports.com
      tags: latest
  - name: deploy site
    image: appleboy/drone-ssh
    settings:
      host:
        - 172.0.17.1
      username: drone
      key:
        from_secret: one_ssh_key
      port: 22
      command_timeout: 2m
      script:
        - cd /var/deploy/prismaticmotorsports.com/
        - docker compose -f compose.dev.yml up --force-recreate -d
